alter table action drop foreign key FKAB2F7E3662335EF5;
alter table action drop foreign key FKAB2F7E36FEB07DB7;
alter table appointment drop foreign key FKA8155B9FF42CD537;
alter table category_answer drop foreign key FKB256861FA02CB97B;
alter table category_answer drop foreign key FKB256861FC25CCD96;
alter table conclusion drop foreign key FK98CF121FFEB07DB7;
alter table consent drop foreign key FK38B6C01AFEB07DB7;
alter table contra_indication drop foreign key FK32A5E37A1A9AC81D;
alter table contra_indication_answer drop foreign key FKF30E5C23F42CD537;
alter table input_source drop foreign key FK43929630576DC9EC;
alter table instrument drop foreign key FK532D63E7576DC9EC;
alter table instrument_computed_output drop foreign key FK593A0A1B8970BEE6;
alter table instrument_computed_output drop foreign key FK593A0A1B97854635;
alter table instrument_parameter drop foreign key FKE62A9D511A9AC81D;
alter table instrument_parameter drop foreign key FKE62A9D511E8A5EAC;
alter table instrument_run drop foreign key FK74A802331A9AC81D;
alter table instrument_run drop foreign key FK74A8023362335EF5;
alter table instrument_run drop foreign key FK74A8023347B0649A;
alter table instrument_run drop foreign key FK74A802333E14D6A0;
alter table instrument_run_value drop foreign key FK55C544656434F6C4;
alter table instrument_run_value drop foreign key FK55C54465AF8DC1E8;
alter table instrument_type_dependencies drop foreign key FK64ABA7B618ABE994;
alter table instrument_type_dependencies drop foreign key FK64ABA7B6576DC9EC;
alter table integrity_check drop foreign key FK4024D996AF8DC1E8;
alter table integrity_check drop foreign key FK4024D9966AF1EEC8;
alter table interview drop foreign key FK1DFCD181F42CD537;
alter table interview drop foreign key FK1DFCD18162335EF5;
alter table multiple_output_parameters drop foreign key FK15812F79E6B32F0A;
alter table multiple_output_parameters drop foreign key FK15812F794EBD80AB;
alter table participant_interview drop foreign key FKD72C9775F42CD537;
alter table question_answer drop foreign key FK561DF237D3F488C2;
alter table questionnaire_participant drop foreign key FK474CFE97F42CD537;
alter table stage_execution_memento drop foreign key FKA9968B113FEC5D39;
alter table stage_execution_memento drop foreign key FKA9968B11FEB07DB7;
alter table user_roles drop foreign key FK73429949BD089B15;
alter table user_roles drop foreign key FK7342994962335EF5;
drop table if exists action;
drop table if exists application_configuration;
drop table if exists appointment;
drop table if exists category_answer;
drop table if exists conclusion;
drop table if exists consent;
drop table if exists contra_indication;
drop table if exists contra_indication_answer;
drop table if exists input_source;
drop table if exists instrument;
drop table if exists instrument_computed_output;
drop table if exists instrument_parameter;
drop table if exists instrument_run;
drop table if exists instrument_run_value;
drop table if exists instrument_type;
drop table if exists instrument_type_dependencies;
drop table if exists integrity_check;
drop table if exists interview;
drop table if exists multiple_output_parameters;
drop table if exists participant;
drop table if exists participant_interview;
drop table if exists question_answer;
drop table if exists questionnaire_participant;
drop table if exists role;
drop table if exists stage_execution_memento;
drop table if exists user;
drop table if exists user_roles;
create table action (id bigint not null auto_increment, comment varchar(255), date_time datetime, event_reason varchar(255), stage varchar(255), type varchar(255), interview_id bigint, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table application_configuration (id bigint not null auto_increment, participant_directory_path varchar(255), site_name varchar(255), site_no varchar(255), study_name varchar(255), primary key (id)) ENGINE=InnoDB;
create table appointment (id bigint not null auto_increment, appointment_code varchar(255), date datetime, participant_id bigint, primary key (id)) ENGINE=InnoDB;
create table category_answer (id bigint not null auto_increment, active bit, category_name varchar(255), data_type integer, date_value datetime, decimal_value double precision, integer_value bigint, occurence integer, text_value varchar(255), parent_category_answer_id bigint, question_answer_id bigint, primary key (id)) ENGINE=InnoDB;
create table conclusion (id bigint not null auto_increment, accepted bit, barcode varchar(255), interview_id bigint, primary key (id)) ENGINE=InnoDB;
create table consent (id bigint not null auto_increment, accepted bit, language varchar(255), mode integer, interview_id bigint, primary key (id)) ENGINE=InnoDB;
create table contra_indication (id bigint not null auto_increment, description varchar(200), name varchar(200), type varchar(255), instrument_id bigint, primary key (id)) ENGINE=InnoDB;
create table contra_indication_answer (id bigint not null auto_increment, contra_indicated bit, contra_indication tinyblob, participant_id bigint, primary key (id)) ENGINE=InnoDB;
create table input_source (input_source_type varchar(31) not null, id bigint not null auto_increment, choices varchar(255), property varchar(200), parameter_name varchar(200), value varchar(200), instrument_type_id bigint, primary key (id)) ENGINE=InnoDB;
create table instrument (id bigint not null auto_increment, barcode varchar(200), model varchar(200), name varchar(200), serial_number varchar(200), status varchar(255), vendor varchar(200), instrument_type_id bigint, primary key (id), unique (barcode)) ENGINE=InnoDB;
create table instrument_computed_output (instrument_computed_output_parameter_id bigint not null, instrument_output_parameter_id bigint not null) ENGINE=InnoDB;
create table instrument_parameter (instrument_parameter_type varchar(100) not null, id bigint not null auto_increment, capture_method varchar(255), data_type varchar(255), description varchar(200), measurement_unit varchar(20), name varchar(200), type varchar(255), algorithm varchar(255), instrument_id bigint, input_source_id bigint, primary key (id)) ENGINE=InnoDB;
create table instrument_run (id bigint not null auto_increment, other_contra_indication varchar(255), refusal_reason varchar(255), refusal_reason_comment varchar(2000), status varchar(255), time_end datetime, time_start datetime, contra_indication_id bigint, instrument_id bigint, participant_interview_id bigint, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table instrument_run_value (id bigint not null auto_increment, boolean_value bit, capture_method varchar(255), data_value longblob, date_value datetime, decimal_value double precision, integer_value bigint, text_value varchar(2000), value_integrity varchar(255), instrument_parameter_id bigint, instrument_run_id bigint, primary key (id)) ENGINE=InnoDB;
create table instrument_type (id bigint not null auto_increment, description varchar(200), name varchar(200), primary key (id), unique (name)) ENGINE=InnoDB;
create table instrument_type_dependencies (instrument_type_id bigint not null, depends_on_instrument_type_id bigint not null) ENGINE=InnoDB;
create table integrity_check (integrity_check_type varchar(100) not null, id bigint not null auto_increment, customized_description varchar(255), type varchar(255), decimal_max_value_female double precision, decimal_max_value_male double precision, decimal_min_value_female double precision, decimal_min_value_male double precision, integer_max_value_female bigint, integer_max_value_male bigint, integer_min_value_female bigint, integer_min_value_male bigint, offset integer, percent integer, boolean_value bit, date_value datetime, decimal_value double precision, integer_value bigint, text_value varchar(255), instrument_parameter_id bigint, parameter bigint, primary key (id)) ENGINE=InnoDB;
create table interview (id bigint not null auto_increment, closed bit, end_date datetime, start_date datetime, status varchar(255), participant_id bigint, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table multiple_output_parameters (multiple_output_parameter_source_id bigint not null, output_parameter_source_id bigint not null) ENGINE=InnoDB;
create table participant (id bigint not null auto_increment, apartment varchar(255), barcode varchar(255), birth_date date, city varchar(255), country varchar(255), enrollment_id varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), phone varchar(255), postal_code varchar(255), province varchar(255), site_no varchar(255), street varchar(255), primary key (id), unique (barcode, enrollment_id)) ENGINE=InnoDB;
create table participant_interview (id bigint not null auto_increment, participant_id bigint, primary key (id)) ENGINE=InnoDB;
create table question_answer (id bigint not null auto_increment, comment varchar(255), question_name varchar(255), questionnaire_participant_id bigint, primary key (id)) ENGINE=InnoDB;
create table questionnaire_participant (id bigint not null auto_increment, locale varchar(255), questionnaire_name varchar(255), questionnaire_version varchar(255), resume_page varchar(255), participant_id bigint, primary key (id)) ENGINE=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), primary key (id)) ENGINE=InnoDB;
create table stage_execution_memento (id bigint not null auto_increment, stage varchar(255), state varchar(255), action_id bigint, interview_id bigint, primary key (id)) ENGINE=InnoDB;
create table user (id bigint not null auto_increment, deleted bit, email varchar(255), first_name varchar(255), language varchar(255), last_name varchar(255), login varchar(255), password varchar(255), status varchar(255), primary key (id)) ENGINE=InnoDB;
create table user_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) ENGINE=InnoDB;
alter table action add index FKAB2F7E3662335EF5 (user_id), add constraint FKAB2F7E3662335EF5 foreign key (user_id) references user (id);
alter table action add index FKAB2F7E36FEB07DB7 (interview_id), add constraint FKAB2F7E36FEB07DB7 foreign key (interview_id) references interview (id);
alter table appointment add index FKA8155B9FF42CD537 (participant_id), add constraint FKA8155B9FF42CD537 foreign key (participant_id) references participant (id);
alter table category_answer add index FKB256861FA02CB97B (parent_category_answer_id), add constraint FKB256861FA02CB97B foreign key (parent_category_answer_id) references category_answer (id);
alter table category_answer add index FKB256861FC25CCD96 (question_answer_id), add constraint FKB256861FC25CCD96 foreign key (question_answer_id) references question_answer (id);
alter table conclusion add index FK98CF121FFEB07DB7 (interview_id), add constraint FK98CF121FFEB07DB7 foreign key (interview_id) references interview (id);
alter table consent add index FK38B6C01AFEB07DB7 (interview_id), add constraint FK38B6C01AFEB07DB7 foreign key (interview_id) references interview (id);
create index name_index on contra_indication (name);
alter table contra_indication add index FK32A5E37A1A9AC81D (instrument_id), add constraint FK32A5E37A1A9AC81D foreign key (instrument_id) references instrument (id);
alter table contra_indication_answer add index FKF30E5C23F42CD537 (participant_id), add constraint FKF30E5C23F42CD537 foreign key (participant_id) references participant (id);
alter table input_source add index FK43929630576DC9EC (instrument_type_id), add constraint FK43929630576DC9EC foreign key (instrument_type_id) references instrument_type (id);
create index name_index on instrument (name);
alter table instrument add index FK532D63E7576DC9EC (instrument_type_id), add constraint FK532D63E7576DC9EC foreign key (instrument_type_id) references instrument_type (id);
alter table instrument_computed_output add index FK593A0A1B8970BEE6 (instrument_computed_output_parameter_id), add constraint FK593A0A1B8970BEE6 foreign key (instrument_computed_output_parameter_id) references instrument_parameter (id);
alter table instrument_computed_output add index FK593A0A1B97854635 (instrument_output_parameter_id), add constraint FK593A0A1B97854635 foreign key (instrument_output_parameter_id) references instrument_parameter (id);
create index name_index on instrument_parameter (name);
alter table instrument_parameter add index FKE62A9D511A9AC81D (instrument_id), add constraint FKE62A9D511A9AC81D foreign key (instrument_id) references instrument (id);
alter table instrument_parameter add index FKE62A9D511E8A5EAC (input_source_id), add constraint FKE62A9D511E8A5EAC foreign key (input_source_id) references input_source (id);
alter table instrument_run add index FK74A802331A9AC81D (instrument_id), add constraint FK74A802331A9AC81D foreign key (instrument_id) references instrument (id);
alter table instrument_run add index FK74A8023362335EF5 (user_id), add constraint FK74A8023362335EF5 foreign key (user_id) references user (id);
alter table instrument_run add index FK74A8023347B0649A (participant_interview_id), add constraint FK74A8023347B0649A foreign key (participant_interview_id) references participant_interview (id);
alter table instrument_run add index FK74A802333E14D6A0 (contra_indication_id), add constraint FK74A802333E14D6A0 foreign key (contra_indication_id) references contra_indication (id);
alter table instrument_run_value add index FK55C544656434F6C4 (instrument_run_id), add constraint FK55C544656434F6C4 foreign key (instrument_run_id) references instrument_run (id);
alter table instrument_run_value add index FK55C54465AF8DC1E8 (instrument_parameter_id), add constraint FK55C54465AF8DC1E8 foreign key (instrument_parameter_id) references instrument_parameter (id);
create index name_index on instrument_type (name);
alter table instrument_type_dependencies add index FK64ABA7B618ABE994 (depends_on_instrument_type_id), add constraint FK64ABA7B618ABE994 foreign key (depends_on_instrument_type_id) references instrument_type (id);
alter table instrument_type_dependencies add index FK64ABA7B6576DC9EC (instrument_type_id), add constraint FK64ABA7B6576DC9EC foreign key (instrument_type_id) references instrument_type (id);
alter table integrity_check add index FK4024D996AF8DC1E8 (instrument_parameter_id), add constraint FK4024D996AF8DC1E8 foreign key (instrument_parameter_id) references instrument_parameter (id);
alter table integrity_check add index FK4024D9966AF1EEC8 (parameter), add constraint FK4024D9966AF1EEC8 foreign key (parameter) references instrument_parameter (id);
alter table interview add index FK1DFCD181F42CD537 (participant_id), add constraint FK1DFCD181F42CD537 foreign key (participant_id) references participant (id);
alter table interview add index FK1DFCD18162335EF5 (user_id), add constraint FK1DFCD18162335EF5 foreign key (user_id) references user (id);
alter table multiple_output_parameters add index FK15812F79E6B32F0A (multiple_output_parameter_source_id), add constraint FK15812F79E6B32F0A foreign key (multiple_output_parameter_source_id) references input_source (id);
alter table multiple_output_parameters add index FK15812F794EBD80AB (output_parameter_source_id), add constraint FK15812F794EBD80AB foreign key (output_parameter_source_id) references input_source (id);
alter table participant_interview add index FKD72C9775F42CD537 (participant_id), add constraint FKD72C9775F42CD537 foreign key (participant_id) references participant (id);
alter table question_answer add index FK561DF237D3F488C2 (questionnaire_participant_id), add constraint FK561DF237D3F488C2 foreign key (questionnaire_participant_id) references questionnaire_participant (id);
alter table questionnaire_participant add index FK474CFE97F42CD537 (participant_id), add constraint FK474CFE97F42CD537 foreign key (participant_id) references participant (id);
alter table stage_execution_memento add index FKA9968B113FEC5D39 (action_id), add constraint FKA9968B113FEC5D39 foreign key (action_id) references action (id);
alter table stage_execution_memento add index FKA9968B11FEB07DB7 (interview_id), add constraint FKA9968B11FEB07DB7 foreign key (interview_id) references interview (id);
alter table user_roles add index FK73429949BD089B15 (role_id), add constraint FK73429949BD089B15 foreign key (role_id) references role (id);
alter table user_roles add index FK7342994962335EF5 (user_id), add constraint FK7342994962335EF5 foreign key (user_id) references user (id);
