alter table action drop foreign key FKAB2F7E36400A25DB;
alter table action drop foreign key FKAB2F7E3662335EF5;
alter table action drop foreign key FKAB2F7E36FEB07DB7;
alter table appointment drop foreign key FKA8155B9FF42CD537;
alter table input_source drop foreign key FK43929630576DC9EC;
alter table instrument drop foreign key FK532D63E7576DC9EC;
alter table instrument_computed_output drop foreign key FK593A0A1B8970BEE6;
alter table instrument_computed_output drop foreign key FK593A0A1B97854635;
alter table instrument_parameter drop foreign key FKE62A9D511A9AC81D;
alter table instrument_parameter drop foreign key FKE62A9D511E8A5EAC;
alter table instrument_run drop foreign key FK74A802331A9AC81D;
alter table instrument_run drop foreign key FK74A8023362335EF5;
alter table instrument_run drop foreign key FK74A8023347B0649A;
alter table instrument_run_value drop foreign key FK55C544656434F6C4;
alter table instrument_run_value drop foreign key FK55C54465AF8DC1E8;
alter table instrument_type_dependencies drop foreign key FK64ABA7B618ABE994;
alter table instrument_type_dependencies drop foreign key FK64ABA7B6576DC9EC;
alter table interview drop foreign key FK1DFCD181F42CD537;
alter table interview drop foreign key FK1DFCD18162335EF5;
alter table participant_interview drop foreign key FKD72C9775F42CD537;
alter table stage_dependencies drop foreign key FK3734F0CACFD43783;
alter table stage_dependencies drop foreign key FK3734F0CA400A25DB;
alter table stage_execution_memento drop foreign key FKA9968B11400A25DB;
alter table stage_execution_memento drop foreign key FKA9968B11FEB07DB7;
alter table stage_interview drop foreign key FKB1A769809CC9BF1A;
alter table stage_interview drop foreign key FKB1A76980A1F0E478;
drop table if exists action;
drop table if exists app_configuration;
drop table if exists appointment;
drop table if exists input_source;
drop table if exists instrument;
drop table if exists instrument_computed_output;
drop table if exists instrument_parameter;
drop table if exists instrument_run;
drop table if exists instrument_run_value;
drop table if exists instrument_type;
drop table if exists instrument_type_dependencies;
drop table if exists interview;
drop table if exists participant;
drop table if exists participant_interview;
drop table if exists stage;
drop table if exists stage_dependencies;
drop table if exists stage_execution_memento;
drop table if exists stage_interview;
drop table if exists user;
create table action (id bigint not null auto_increment, comment varchar(255), date_time datetime, event_reason varchar(255), type varchar(255), interview_id bigint, stage_id bigint, user_id bigint, primary key (id)) type=InnoDB;
create table app_configuration (id bigint not null auto_increment, site_name varchar(255), site_no varchar(255), study_name varchar(255), primary key (id)) type=InnoDB;
create table appointment (id bigint not null auto_increment, appointment_code varchar(255), date datetime, participant_id bigint, primary key (id)) type=InnoDB;
create table input_source (input_source_type varchar(31) not null, id bigint not null auto_increment, property varchar(200), parameter_name varchar(200), value varchar(200), instrument_type_id bigint, primary key (id)) type=InnoDB;
create table instrument (id bigint not null auto_increment, barcode varchar(200), model varchar(200), name varchar(200), serial_number varchar(200), status varchar(255), vendor varchar(200), instrument_type_id bigint, primary key (id), unique (barcode)) type=InnoDB;
create table instrument_computed_output (instrument_computed_output_parameter_id bigint not null, instrument_output_parameter_id bigint not null) type=InnoDB;
create table instrument_parameter (instrument_parameter_type varchar(100) not null, id bigint not null auto_increment, capture_method varchar(255), data_type varchar(255), description varchar(200), measurement_unit varchar(20), name varchar(200), algorithm varchar(255), instrument_id bigint, input_source_id bigint, primary key (id)) type=InnoDB;
create table instrument_run (id bigint not null auto_increment, refusal_reason varchar(255), refusal_reason_comment text, status varchar(255), time_end datetime, time_start datetime, instrument_id bigint, participant_interview_id bigint, user_id bigint, primary key (id)) type=InnoDB;
create table instrument_run_value (id bigint not null auto_increment, boolean_value bit, capture_method varchar(255), data_value longblob, date_value datetime, decimal_value double precision, integer_value bigint, text_value text, value_integrity varchar(255), instrument_parameter_id bigint, instrument_run_id bigint, primary key (id)) type=InnoDB;
create table instrument_type (id bigint not null auto_increment, description varchar(200), name varchar(200), primary key (id), unique (name)) type=InnoDB;
create table instrument_type_dependencies (instrument_type_id bigint not null, depends_on_instrument_type_id bigint not null) type=InnoDB;
create table interview (id bigint not null auto_increment, closed bit, start_date datetime, status varchar(255), stop_date datetime, participant_id bigint, user_id bigint, primary key (id)) type=InnoDB;
create table participant (id bigint not null auto_increment, apartment varchar(255), barcode varchar(255), birth_date date, city varchar(255), country varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), phone varchar(255), postal_code varchar(255), province varchar(255), reception_comment varchar(255), street varchar(255), primary key (id)) type=InnoDB;
create table participant_interview (id bigint not null auto_increment, participant_id bigint, primary key (id)) type=InnoDB;
create table stage (id bigint not null auto_increment, description varchar(255), display_order integer, module varchar(255), name varchar(255), primary key (id)) type=InnoDB;
create table stage_dependencies (stage_id bigint not null, depends_on_stage_id bigint not null) type=InnoDB;
create table stage_execution_memento (id bigint not null auto_increment, state varchar(255), interview_id bigint, stage_id bigint, primary key (id)) type=InnoDB;
create table stage_interview (stage_id bigint not null, interview_id bigint not null) type=InnoDB;
create table user (id bigint not null auto_increment, deleted bit, email varchar(255), language varchar(255), login varchar(255), name varchar(255), password varchar(255), role varchar(30), primary key (id)) type=InnoDB;
alter table action add index FKAB2F7E36400A25DB (stage_id), add constraint FKAB2F7E36400A25DB foreign key (stage_id) references stage (id);
alter table action add index FKAB2F7E3662335EF5 (user_id), add constraint FKAB2F7E3662335EF5 foreign key (user_id) references user (id);
alter table action add index FKAB2F7E36FEB07DB7 (interview_id), add constraint FKAB2F7E36FEB07DB7 foreign key (interview_id) references interview (id);
alter table appointment add index FKA8155B9FF42CD537 (participant_id), add constraint FKA8155B9FF42CD537 foreign key (participant_id) references participant (id);
alter table input_source add index FK43929630576DC9EC (instrument_type_id), add constraint FK43929630576DC9EC foreign key (instrument_type_id) references instrument_type (id);
create index name_index on instrument (name);
alter table instrument add index FK532D63E7576DC9EC (instrument_type_id), add constraint FK532D63E7576DC9EC foreign key (instrument_type_id) references instrument_type (id);
alter table instrument_computed_output add index FK593A0A1B8970BEE6 (instrument_computed_output_parameter_id), add constraint FK593A0A1B8970BEE6 foreign key (instrument_computed_output_parameter_id) references instrument_parameter (id);
alter table instrument_computed_output add index FK593A0A1B97854635 (instrument_output_parameter_id), add constraint FK593A0A1B97854635 foreign key (instrument_output_parameter_id) references instrument_parameter (id);
create index name_index on instrument_parameter (name);
alter table instrument_parameter add index FKE62A9D511A9AC81D (instrument_id), add constraint FKE62A9D511A9AC81D foreign key (instrument_id) references instrument (id);
alter table instrument_parameter add index FKE62A9D511E8A5EAC (input_source_id), add constraint FKE62A9D511E8A5EAC foreign key (input_source_id) references input_source (id);
alter table instrument_run add index FK74A802331A9AC81D (instrument_id), add constraint FK74A802331A9AC81D foreign key (instrument_id) references instrument (id);
alter table instrument_run add index FK74A8023362335EF5 (user_id), add constraint FK74A8023362335EF5 foreign key (user_id) references user (id);
alter table instrument_run add index FK74A8023347B0649A (participant_interview_id), add constraint FK74A8023347B0649A foreign key (participant_interview_id) references participant_interview (id);
alter table instrument_run_value add index FK55C544656434F6C4 (instrument_run_id), add constraint FK55C544656434F6C4 foreign key (instrument_run_id) references instrument_run (id);
alter table instrument_run_value add index FK55C54465AF8DC1E8 (instrument_parameter_id), add constraint FK55C54465AF8DC1E8 foreign key (instrument_parameter_id) references instrument_parameter (id);
create index name_index on instrument_type (name);
alter table instrument_type_dependencies add index FK64ABA7B618ABE994 (depends_on_instrument_type_id), add constraint FK64ABA7B618ABE994 foreign key (depends_on_instrument_type_id) references instrument_type (id);
alter table instrument_type_dependencies add index FK64ABA7B6576DC9EC (instrument_type_id), add constraint FK64ABA7B6576DC9EC foreign key (instrument_type_id) references instrument_type (id);
alter table interview add index FK1DFCD181F42CD537 (participant_id), add constraint FK1DFCD181F42CD537 foreign key (participant_id) references participant (id);
alter table interview add index FK1DFCD18162335EF5 (user_id), add constraint FK1DFCD18162335EF5 foreign key (user_id) references user (id);
alter table participant_interview add index FKD72C9775F42CD537 (participant_id), add constraint FKD72C9775F42CD537 foreign key (participant_id) references participant (id);
alter table stage_dependencies add index FK3734F0CACFD43783 (depends_on_stage_id), add constraint FK3734F0CACFD43783 foreign key (depends_on_stage_id) references stage (id);
alter table stage_dependencies add index FK3734F0CA400A25DB (stage_id), add constraint FK3734F0CA400A25DB foreign key (stage_id) references stage (id);
alter table stage_execution_memento add index FKA9968B11400A25DB (stage_id), add constraint FKA9968B11400A25DB foreign key (stage_id) references stage (id);
alter table stage_execution_memento add index FKA9968B11FEB07DB7 (interview_id), add constraint FKA9968B11FEB07DB7 foreign key (interview_id) references interview (id);
alter table stage_interview add index FKB1A769809CC9BF1A (stage_id), add constraint FKB1A769809CC9BF1A foreign key (stage_id) references interview (id);
alter table stage_interview add index FKB1A76980A1F0E478 (interview_id), add constraint FKB1A76980A1F0E478 foreign key (interview_id) references stage (id);
